[build]
command = "pnpm run build:client"
functions = "netlify/functions"
publish = "dist/spa"


[functions]
node_bundler = "esbuild"
[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"

[[redirects]]
force = true
from = "/robots.txt"
status = 200
to = "/.netlify/functions/api/robots.txt"

[[redirects]]
force = true
from = "/sitemap.xml"
status = 200
to = "/.netlify/functions/api/sitemap.xml"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
